package app

import (
	"context"
	"fmt"
	"strings"
)

// Migrate creates the portable baseline schema. UUIDs are generated by the
// application, which avoids database-specific UUID extensions and lets the
// same model run on PostgreSQL, MySQL and SQLite.
func (s *Store) Migrate(ctx context.Context) error {
	if s.db.Dialector.Name() == "sqlite" {
		if err := s.db.WithContext(ctx).Exec("PRAGMA foreign_keys = ON").Error; err != nil {
			return err
		}
	}
	if err := s.migrateLegacyAccountNames(ctx); err != nil {
		return err
	}
	if err := s.migrateChannelDispatch(ctx); err != nil {
		return err
	}
	if err := s.db.WithContext(ctx).AutoMigrate(
		&Account{}, &User{}, &PaymentChannel{}, &Bill{}, &Refund{},
		&WebhookEvent{}, &AuditLog{}, &SystemSetting{}, &AccountSetting{},
	); err != nil {
		return fmt.Errorf("auto migrate schema: %w", err)
	}
	if err := s.migrateUsernames(ctx); err != nil {
		return err
	}
	var administrators int64
	if err := s.db.WithContext(ctx).Model(&User{}).Where("role = ?", "platform_admin").Count(&administrators).Error; err != nil {
		return err
	}
	if administrators == 0 {
		var first User
		if err := s.db.WithContext(ctx).Order("created_at ASC").First(&first).Error; err == nil {
			if err := s.db.WithContext(ctx).Model(&User{}).Where("id = ?", first.ID).Update("role", "platform_admin").Error; err != nil {
				return err
			}
		}
	}
	return nil
}

func (s *Store) migrateUsernames(ctx context.Context) error {
	var users []User
	if err := s.db.WithContext(ctx).Where("username IS NULL OR username = ''").Find(&users).Error; err != nil {
		return err
	}
	for _, user := range users {
		base := strings.Split(strings.ToLower(user.Email), "@")[0]
		base = strings.Map(func(r rune) rune {
			if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '_' || r == '-' {
				return r
			}
			return '-'
		}, base)
		base = strings.Trim(base, "-_")
		if base == "" {
			base = "user"
		}
		candidate := base
		for suffix := 1; ; suffix++ {
			var count int64
			if err := s.db.WithContext(ctx).Model(&User{}).Where("username = ? AND id <> ?", candidate, user.ID).Count(&count).Error; err != nil {
				return err
			}
			if count == 0 {
				break
			}
			candidate = fmt.Sprintf("%s-%d", base, suffix+1)
		}
		if err := s.db.WithContext(ctx).Model(&User{}).Where("id = ?", user.ID).Update("username", candidate).Error; err != nil {
			return err
		}
	}
	return nil
}

// Earlier releases enforced a single channel for each provider. Removing that
// uniqueness is required before AutoMigrate can add priority and weight.
func (s *Store) migrateChannelDispatch(ctx context.Context) error {
	migrator := s.db.WithContext(ctx).Migrator()
	if !migrator.HasTable(&PaymentChannel{}) {
		return nil
	}
	for _, name := range []string{"idx_account_provider", "payment_channels_account_id_provider_key", "payment_channels_account_id_provider_unique"} {
		if migrator.HasConstraint(&PaymentChannel{}, name) {
			if err := migrator.DropConstraint(&PaymentChannel{}, name); err != nil {
				return fmt.Errorf("remove legacy payment channel constraint %s: %w", name, err)
			}
		}
		if migrator.HasIndex(&PaymentChannel{}, name) {
			if err := migrator.DropIndex(&PaymentChannel{}, name); err != nil {
				return fmt.Errorf("remove legacy payment channel index %s: %w", name, err)
			}
		}
	}
	return nil
}

// migrateLegacyAccountNames upgrades databases created before the user-account
// terminology change without discarding payment data. GORM selects the proper
// ALTER syntax for PostgreSQL, MySQL, and SQLite.
func (s *Store) migrateLegacyAccountNames(ctx context.Context) error {
	migrator := s.db.WithContext(ctx).Migrator()
	if migrator.HasTable("tenants") && !migrator.HasTable("accounts") {
		if err := migrator.RenameTable("tenants", "accounts"); err != nil {
			return fmt.Errorf("rename legacy accounts table: %w", err)
		}
	}
	for _, table := range []string{"users", "payment_channels", "bills", "refunds", "webhook_events", "audit_logs", "account_settings"} {
		if migrator.HasTable(table) && migrator.HasColumn(table, "tenant_id") && !migrator.HasColumn(table, "account_id") {
			if err := migrator.RenameColumn(table, "tenant_id", "account_id"); err != nil {
				return fmt.Errorf("rename %s.tenant_id: %w", table, err)
			}
		}
	}
	return nil
}
