package app

import (
	"context"
	"fmt"
)

// Migrate creates the portable baseline schema. UUIDs are generated by the
// application, which avoids database-specific UUID extensions and lets the
// same model run on PostgreSQL, MySQL and SQLite.
func (s *Store) Migrate(ctx context.Context) error {
	if s.db.Dialector.Name() == "sqlite" {
		if err := s.db.WithContext(ctx).Exec("PRAGMA foreign_keys = ON").Error; err != nil {
			return err
		}
	}
	if err := s.migrateLegacyAccountNames(ctx); err != nil {
		return err
	}
	if err := s.migrateChannelDispatch(ctx); err != nil {
		return err
	}
	if err := s.db.WithContext(ctx).AutoMigrate(
		&Account{}, &User{}, &PaymentChannel{}, &Bill{}, &Refund{},
		&WebhookEvent{}, &AuditLog{}, &SystemSetting{}, &AccountSetting{},
	); err != nil {
		return fmt.Errorf("auto migrate schema: %w", err)
	}
	return nil
}

// Earlier releases enforced a single channel for each provider. Removing that
// uniqueness is required before AutoMigrate can add priority and weight.
func (s *Store) migrateChannelDispatch(ctx context.Context) error {
	migrator := s.db.WithContext(ctx).Migrator()
	if !migrator.HasTable(&PaymentChannel{}) {
		return nil
	}
	for _, name := range []string{"idx_account_provider", "payment_channels_account_id_provider_key", "payment_channels_account_id_provider_unique"} {
		if migrator.HasConstraint(&PaymentChannel{}, name) {
			if err := migrator.DropConstraint(&PaymentChannel{}, name); err != nil {
				return fmt.Errorf("remove legacy payment channel constraint %s: %w", name, err)
			}
		}
		if migrator.HasIndex(&PaymentChannel{}, name) {
			if err := migrator.DropIndex(&PaymentChannel{}, name); err != nil {
				return fmt.Errorf("remove legacy payment channel index %s: %w", name, err)
			}
		}
	}
	return nil
}

// migrateLegacyAccountNames upgrades databases created before the user-account
// terminology change without discarding payment data. GORM selects the proper
// ALTER syntax for PostgreSQL, MySQL, and SQLite.
func (s *Store) migrateLegacyAccountNames(ctx context.Context) error {
	migrator := s.db.WithContext(ctx).Migrator()
	if migrator.HasTable("tenants") && !migrator.HasTable("accounts") {
		if err := migrator.RenameTable("tenants", "accounts"); err != nil {
			return fmt.Errorf("rename legacy accounts table: %w", err)
		}
	}
	for _, table := range []string{"users", "payment_channels", "bills", "refunds", "webhook_events", "audit_logs", "account_settings"} {
		if migrator.HasTable(table) && migrator.HasColumn(table, "tenant_id") && !migrator.HasColumn(table, "account_id") {
			if err := migrator.RenameColumn(table, "tenant_id", "account_id"); err != nil {
				return fmt.Errorf("rename %s.tenant_id: %w", table, err)
			}
		}
	}
	return nil
}
