package app

import (
	"context"
	"fmt"
	"strings"
)

// Migrate creates the portable baseline schema. UUIDs are generated by the
// application, which avoids database-specific UUID extensions and lets the
// same model run on PostgreSQL, MySQL and SQLite.
func (s *Store) Migrate(ctx context.Context) error {
	if s.db.Dialector.Name() == "sqlite" {
		if err := s.db.WithContext(ctx).Exec("PRAGMA foreign_keys = ON").Error; err != nil {
			return err
		}
	}
	for _, statement := range portableSchema {
		if s.db.Dialector.Name() == "mysql" && strings.HasPrefix(statement, "CREATE INDEX IF NOT EXISTS") {
			statement = strings.Replace(statement, " IF NOT EXISTS", "", 1)
		}
		if err := s.db.WithContext(ctx).Exec(statement).Error; err != nil {
			if strings.HasPrefix(statement, "CREATE INDEX") && isUniqueViolation(err) {
				continue
			}
			return fmt.Errorf("apply schema: %w", err)
		}
	}
	return nil
}

var portableSchema = []string{
	`CREATE TABLE IF NOT EXISTS tenants (id VARCHAR(36) PRIMARY KEY, name VARCHAR(120) NOT NULL, merchant_no VARCHAR(64) NOT NULL UNIQUE, status VARCHAR(16) NOT NULL DEFAULT 'active', api_secret_ciphertext TEXT NOT NULL, callback_secret_ciphertext TEXT NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
	`CREATE TABLE IF NOT EXISTS users (id VARCHAR(36) PRIMARY KEY, tenant_id VARCHAR(36), email VARCHAR(255) NOT NULL UNIQUE, password_hash TEXT NOT NULL, display_name VARCHAR(120) NOT NULL, role VARCHAR(32) NOT NULL, is_active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE)`,
	`CREATE TABLE IF NOT EXISTS payment_channels (id VARCHAR(36) PRIMARY KEY, tenant_id VARCHAR(36) NOT NULL, provider VARCHAR(16) NOT NULL, display_name VARCHAR(120) NOT NULL, enabled BOOLEAN NOT NULL DEFAULT FALSE, config_ciphertext TEXT NOT NULL DEFAULT '', webhook_token VARCHAR(80) NOT NULL UNIQUE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE (tenant_id, provider), FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE)`,
	`CREATE TABLE IF NOT EXISTS bills (id VARCHAR(36) PRIMARY KEY, tenant_id VARCHAR(36) NOT NULL, channel_id VARCHAR(36) NOT NULL, platform_order_no VARCHAR(64) NOT NULL UNIQUE, merchant_order_no VARCHAR(128) NOT NULL, subject VARCHAR(256) NOT NULL, description VARCHAR(512) NOT NULL DEFAULT '', amount_minor BIGINT NOT NULL, currency CHAR(3) NOT NULL DEFAULT 'CNY', provider VARCHAR(16) NOT NULL, scene VARCHAR(16) NOT NULL, status VARCHAR(16) NOT NULL DEFAULT 'pending', provider_transaction_id VARCHAR(128), provider_payload TEXT NOT NULL DEFAULT '{}', notify_url TEXT NOT NULL, return_url TEXT, metadata TEXT, expires_at TIMESTAMP NULL, paid_at TIMESTAMP NULL, closed_at TIMESTAMP NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE (tenant_id, merchant_order_no), FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE, FOREIGN KEY (channel_id) REFERENCES payment_channels(id))`,
	`CREATE TABLE IF NOT EXISTS refunds (id VARCHAR(36) PRIMARY KEY, tenant_id VARCHAR(36) NOT NULL, bill_id VARCHAR(36) NOT NULL, refund_order_no VARCHAR(128) NOT NULL, amount_minor BIGINT NOT NULL, reason VARCHAR(256) NOT NULL DEFAULT '', status VARCHAR(16) NOT NULL DEFAULT 'pending', provider_refund_id VARCHAR(128), provider_payload TEXT NOT NULL DEFAULT '{}', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE (tenant_id, refund_order_no), FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE, FOREIGN KEY (bill_id) REFERENCES bills(id))`,
	`CREATE TABLE IF NOT EXISTS webhook_events (id VARCHAR(36) PRIMARY KEY, tenant_id VARCHAR(36) NOT NULL, channel_id VARCHAR(36) NOT NULL, provider VARCHAR(16) NOT NULL, event_key VARCHAR(200) NOT NULL, verified BOOLEAN NOT NULL DEFAULT FALSE, payload TEXT NOT NULL, processed_at TIMESTAMP NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE (channel_id, event_key), FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE, FOREIGN KEY (channel_id) REFERENCES payment_channels(id))`,
	`CREATE TABLE IF NOT EXISTS audit_logs (id VARCHAR(36) PRIMARY KEY, tenant_id VARCHAR(36) NULL, actor_user_id VARCHAR(36) NULL, action VARCHAR(100) NOT NULL, target_type VARCHAR(64) NOT NULL, target_id VARCHAR(128) NOT NULL, request_id VARCHAR(64) NOT NULL, detail TEXT NOT NULL DEFAULT '{}', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL, FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL)`,
	`CREATE INDEX IF NOT EXISTS bills_tenant_created_idx ON bills(tenant_id, created_at)`,
	`CREATE INDEX IF NOT EXISTS bills_tenant_status_idx ON bills(tenant_id, status)`,
	`CREATE INDEX IF NOT EXISTS refunds_bill_idx ON refunds(bill_id, created_at)`,
	`CREATE INDEX IF NOT EXISTS webhook_events_channel_idx ON webhook_events(channel_id, created_at)`,
	`CREATE INDEX IF NOT EXISTS audit_logs_tenant_created_idx ON audit_logs(tenant_id, created_at)`,
}
