import { useState } from "react"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Switch } from "@/components/ui/switch"
import { Textarea } from "@/components/ui/textarea"
import { Empty, Modal } from "@/components/page-ui"
import { providerName } from "@/lib/api"
import type { ApiRequest, Channel, Account } from "@/types"

export function ChannelsPage({ data, account, canManage, request, onRefresh }: { data: Channel[]; account?: Account; canManage: boolean; request: ApiRequest; onRefresh: () => void }) {
  const [adding, setAdding] = useState(false); const [editing, setEditing] = useState<Channel | null>(null)
  if (!account) return <div className="content"><Empty icon="◈" title="用户不可用" copy="请重新登录后再配置支付通道。" /></div>
  return <div className="content"><section className="account-banner"><div><p className="eyebrow">当前用户</p><h3>{account.name}</h3><span>商户号 {account.merchant_no}</span></div>{canManage && <button className="primary-button" onClick={() => setAdding(true)}>新增通道</button>}</section><section className="channel-grid">{data.map((channel) => <article className="channel-card" key={channel.id}><div className="channel-card-top"><span className={`large-provider ${channel.provider}`}>{channel.provider === "alipay" ? "支" : "微"}</span><span className={`status ${channel.enabled ? "paid" : "pending"}`}>{channel.enabled ? "已启用" : "未启用"}</span></div><h3>{channel.display_name}</h3><p>{channel.configured ? "已保存官方凭据。" : "尚未填写官方凭据。"}</p><div className="channel-meta"><span>{providerName[channel.provider]}</span>{canManage && <button className="text-button" onClick={() => setEditing(channel)}>配置通道 →</button>}</div></article>)}</section>{!data.length && <Empty icon="◈" title="尚未添加支付通道" copy="添加支付宝或微信支付通道后，填写可视化官方凭据即可开始收款。" />}{adding && <AddChannel onClose={() => setAdding(false)} onSaved={() => { setAdding(false); onRefresh() }} request={request}/>} {editing && <ChannelConfig channel={editing} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); onRefresh() }} request={request}/>}</div>
}
function AddChannel({ request, onClose, onSaved }: { request: ApiRequest; onClose: () => void; onSaved: () => void }) { const [provider, setProvider] = useState("alipay"); const [displayName, setDisplayName] = useState("支付宝"); const [error, setError] = useState(""); async function save() { try { await request("/api/v1/admin/channels", { method: "POST", body: JSON.stringify({ provider, display_name: displayName }) }); onSaved() } catch (err: any) { setError(err.message) } } return <Modal title="新增支付通道" onClose={onClose}><Label className="form-label">支付服务商<Select value={provider} onValueChange={(value) => { if (value) { setProvider(value); setDisplayName(value === "alipay" ? "支付宝" : "微信支付") } }}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="alipay">支付宝</SelectItem><SelectItem value="wechat">微信支付</SelectItem></SelectContent></Select></Label><Label className="form-label">展示名称<Input value={displayName} onChange={(event) => setDisplayName(event.target.value)} /></Label>{error && <p className="form-error">{error}</p>}<button className="primary-button full" onClick={save}>添加并配置</button></Modal> }
function ChannelConfig({ channel, request, onClose, onSaved }: { channel: Channel; request: ApiRequest; onClose: () => void; onSaved: () => void }) { const [name, setName] = useState(channel.display_name); const [enabled, setEnabled] = useState(channel.enabled); const [values, setValues] = useState<Record<string, string>>({}); const [error, setError] = useState(""); const set = (key: string, value: string) => setValues((current) => ({ ...current, [key]: value })); const alipay = channel.provider === "alipay"; async function save() { const config = alipay ? { alipay: { app_id: values.app_id || "", app_private_key_pem: values.app_private_key_pem || "", alipay_public_key_pem: values.alipay_public_key_pem || "", gateway_url: values.gateway_url || "", return_url: values.return_url || "" } } : { wechat: { mch_id: values.mch_id || "", app_id: values.app_id || "", merchant_serial_no: values.merchant_serial_no || "", merchant_private_key_pem: values.merchant_private_key_pem || "", api_v3_key: values.api_v3_key || "", platform_public_key_pem: values.platform_public_key_pem || "", platform_serial_no: values.platform_serial_no || "" } }; try { await request(`/api/v1/admin/channels/${channel.id}`, { method: "PATCH", body: JSON.stringify({ display_name: name, enabled, ...(Object.keys(values).length ? { config } : {}) }) }); onSaved() } catch (err: any) { setError(err.message) } } const field = (label: string, key: string, secret = false) => <Label className="form-label" key={key}>{label}<Input type={secret ? "password" : "text"} value={values[key] || ""} onChange={(event) => set(key, event.target.value)} /></Label>; const pem = (label: string, key: string) => <Label className="form-label" key={key}>{label}<Textarea rows={4} value={values[key] || ""} onChange={(event) => set(key, event.target.value)} /></Label>; return <Modal title={`配置${providerName[channel.provider]}`} onClose={onClose}><p className="modal-intro">敏感凭据加密保存且不回显；重新填写时请提交完整官方凭据。</p><Label className="form-label">展示名称<Input value={name} onChange={(event) => setName(event.target.value)} /></Label>{alipay ? <>{field("App ID", "app_id")}{pem("应用私钥（PEM）", "app_private_key_pem")}{pem("支付宝公钥（PEM）", "alipay_public_key_pem")}{field("网关地址（可选）", "gateway_url")}{field("同步跳转地址（可选）", "return_url")}</> : <>{field("微信支付商户号", "mch_id")}{field("应用 AppID", "app_id")}{field("商户证书序列号", "merchant_serial_no")}{pem("商户私钥（PEM）", "merchant_private_key_pem")}{field("API v3 密钥", "api_v3_key", true)}{pem("平台公钥（PEM）", "platform_public_key_pem")}{field("平台证书序列号（可选）", "platform_serial_no")}</>}<div className="webhook-copy"><b>回调地址</b><code>{channel.webhook_url}</code></div><div className="switch"><Switch checked={enabled} onCheckedChange={setEnabled}/><span/>完成配置后启用</div>{error && <p className="form-error">{error}</p>}<button className="primary-button full" onClick={save}>保存通道配置</button></Modal> }
